""" Sensor Configuration File

    This file contains hardware specifications for various sensors on lilboi.
    
    The general structure of these specifications is:
    sensor_type
        instances:
            sensor_id_0
                param_1: value
                param_2: value
                ...
            sensor_id_1
            ...
        specs:
           spec_1: value
           spec_2: value
           ...
"""

encoders:
    instances:
        left_wheel:
            gpio_pins:
                clk: 6
                dt: 13
        right_wheel:
            gpio_pins:
                clk: 23
                dt: 24
    specifications:
        name: 'KY-040'
        step_size: 0.2094395  # 2*pi/30 (radians)